# Blue line

In [2]:
import cv2
import numpy as np


path=r"""C:\Users\igarg\Desktop\images\blue line.jpg"""


img = cv2.imread(path)

hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)


#Red color rangle  169, 100, 100 , 189, 255, 255


lower_range = np.array([94,80,2])
upper_range = np.array([126,255,255])

mask = cv2.inRange(hsv, lower_range, upper_range)
mask=cv2.resize(mask,(600,400))
img=cv2.resize(img,(600,400))
cv2.imshow('image', img)
cv2.imshow('mask', mask)
print(mask.shape)
print(mask)


cv2.waitKey()
cv2.destroyAllWindows()

(400, 600)
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


# Green color

In [3]:
import cv2
import numpy as np


path=r"""C:\Users\igarg\Desktop\images\green line.jpg"""


img = cv2.imread(path)

hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)


#Red color rangle  169, 100, 100 , 189, 255, 255


lower_range = np.array([25,52,72])
upper_range = np.array([102,255,255])

mask = cv2.inRange(hsv, lower_range, upper_range)
mask=cv2.resize(mask,(600,400))
img=cv2.resize(img,(600,400))
cv2.imshow('image', img)
cv2.imshow('mask', mask)

print(mask.shape)
print(mask)

cv2.waitKey(0)
cv2.destroyAllWindows()

error: OpenCV(4.5.5) D:\a\opencv-python\opencv-python\opencv\modules\highgui\src\window.cpp:1268: error: (-2:Unspecified error) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Cocoa support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function 'cvShowImage'


# Blue and Yellow

In [ ]:
import cv2
import numpy as np


path=r"""C:\Users\igarg\Desktop\images\yellow and blue.jpg"""


img = cv2.imread(path)

hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)


#Red color rangle  169, 100, 100 , 189, 255, 255


lower_range_blue = np.array([94,80,2])
upper_range_blue = np.array([126,255,255])

lower_range_Yellow = np.array([25,50,70])
upper_range_Yellow = np.array([35,255,255])

mask = cv2.inRange(hsv, lower_range_blue, upper_range_blue)
#mask = cv2.inRange(hsv, lower_range_Yellow, upper_range_Yellow)

mask=cv2.resize(mask,(600,400))
img=cv2.resize(img,(600,400))
cv2.imshow('image', img)
cv2.imshow('mask', mask)

print(mask.shape)
print(mask)

cv2.waitKey(0)
cv2.destroyAllWindows()